title: My vZome Designs
author: John Hall
email: j-hall20@sky.com
defaults:
  - scope:
      path: ""
    values:
      # This description will be used for any page/post that does not define its own description in its front-matter.
      description: A webpage with 3D designs created in vZome.  Use your mouse or touch to interact.

# Feel free to select a different theme.
# The "minima" theme is a good default choice just because it
#  generates a list of posts on the home page; many other themes do not.

exclude:
  # Don't generate pages from vZome-created README files,
  #  to avoid generating extra pages in Jekyll, which clutter up the
  #  header for the minima theme, and probably others.
  - 20*/*/*/*/README.md
  
show_excerpts: false #set to true to show excerpts on the homepage
  
minima:
  date_format: "%b %-d, %Y"
 
#social links
social_links:
github_username: ThynStyx

header_pages:
- about.md

theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag
